#!/system/bin/sh

# Перечень команд для редактирования файла cust.img (делалось для Huawei Honor, но
# актуально для любых моделей).
# Требуется root и busybox
# Можно запускать пошагово копированием или одним махом

su

# Подключаем образ во временную папку
mkdir /mnt/cust1
busybox mount -o loop,rw /.cust_backup/image/cust.img /mnt/cust1

# Удаляем вшитые файлы - можно отредактировать по вкусу
rm /mnt/cust1/channel/ru/app/yandexmaps.apk
rm /mnt/cust1/channel/ru/lib/libyandexmaps.so
rm /mnt/cust1/channel/ru/media/bootanimation*.zip

# Отключаем образ
busybox umount /mnt/cust1